# Generated by Django 4.2.6 on 2023-10-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_userposts_author_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposts',
            name='author_details',
        ),
    ]
