# Generated by Django 4.2.6 on 2023-10-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_userposts_author_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Blog/post_images/'),
        ),
    ]
