# Generated by Django 4.2.6 on 2023-10-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_userdetails_image_alter_userdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='about',
            field=models.CharField(default='your description is empty,go to edit profile to add', max_length=300),
        ),
    ]
