# Generated by Django 4.2.6 on 2023-10-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_userdetails_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.userdetails'),
        ),
    ]
