# Generated by Django 4.2.6 on 2023-10-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_userposts_author_details_alter_userposts_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposts',
            name='author',
        ),
    ]
