# Generated by Django 4.2.6 on 2023-10-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_userposts_author_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
