# Generated by Django 4.2.6 on 2023-10-22 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_userposts_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('like_count', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.postcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.userposts')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.userdetails')),
            ],
        ),
    ]
