# Generated by Django 4.2.6 on 2023-10-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
