# Generated by Django 4.2.6 on 2023-11-06 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.status'),
        ),
    ]
