# Generated by Django 4.2.6 on 2023-11-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0022_alter_notification_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lvl', to='Blog.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='userdetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ud', to='Blog.userdetails'),
        ),
    ]
