# Generated by Django 4.2.6 on 2023-11-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0023_userdetails_level_alter_status_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
