# Generated by Django 4.2.6 on 2023-11-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0024_userdetails_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='badge',
            field=models.CharField(default='bronze', max_length=10),
            preserve_default=False,
        ),
    ]
