# Generated by Django 4.2.6 on 2023-11-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0025_userdetails_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='level',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='badge',
            field=models.CharField(default='bronze', max_length=10),
        ),
    ]
