# Generated by Django 4.2.6 on 2023-11-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0026_remove_userdetails_level_alter_userdetails_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='fcount',
            field=models.IntegerField(default=0),
        ),
    ]
